[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
read = [
  { run = 'zathura "$@"', desc = "zathura" },
]
view = [
  { run = 'sxiv "$@"', desc = "sxiv" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },
  { mime = "image/*", use = "view" },

	{ name = "*.json", use = "edit" },
  { name = "*.epub", use = "read" },
  { name = "*.pdf", use = "read" },
	{ name = "*.html", use = [ "open", "edit" ] },
]
